name: minesweeper
description: MineSweeper Game.

publish_to: 'none'

version: 0.2.0+4

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  flex_color_scheme: ^5.0.1
  flutter_native_splash: ^2.2.4
  flutter_riverpod: ^1.0.4
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^5.3.3
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - asset/png/
    - asset/google_font/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#e89ca1"
  image: asset/png/logo.png
  color_dark: "#a26457"
  image_dark: asset/png/logo.png
