name: minezweeper
description: MineSweeper Game.
publish_to: 'none'

version: 0.2.2+6

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.13.4
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  firebase_crashlytics: ^3.4.7
  flex_color_scheme: ^7.3.1
  flutter_native_splash: ^2.3.8
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - asset/png/
    - asset/google_font/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#e89ca1"
  image: asset/png/logo.png
  color_dark: "#a26457"
  image_dark: asset/png/logo.png
