name: minesweeper
description: MineSweeper Game.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  flex_color_scheme: any
  flutter_native_splash: any
  flutter_riverpod: any
  font_awesome_flutter: any
  games_services: any
  google_fonts: any
  google_nav_bar: any
  intl: any
  package_info_plus: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
    - asset/png/
    - asset/google_font/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#e89ca1"
  image: asset/png/logo.png
  color_dark: "#a26457"
  image_dark: asset/png/logo.png
